# volume container to provide consistent storage.
postgres-data:
  image: sameersbn/postgresql:10-2
  command: /bin/true

# a postgres container for providing database access.
postgres:
  container_name: seenit_postgres
  image: sameersbn/postgresql:10-2
  environment:
    - DB_USER=screen
    - DB_PASS=supasecretpassword
    - DB_NAME=screen
    - DB_EXTENSION=pg_trgm,"uuid-ossp"
  ports:
    - '5434:5432'
  volumes_from:
    - postgres-data
  command: -c "max_stack_depth=6MB"
